management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - "prometheus"
          - "health"

server:
  servlet:
    context-path: /SpringBoot-api
