apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jackson-guava
  name: jackson-guava
  namespace: default
spec:
  selector:
    matchLabels:
      app: jackson-guava
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 15%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jackson-guava
    spec:
      containers:
      - name: jackson-guava
        image: quay.io/piano/jackson-guava:latest
        ports:
        - name: liveness-port
          containerPort: 8081
        livenessProbe:
          httpGet:
           path: /health
           port: liveness-port
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          httpGet:
           path: /health
           port: liveness-port
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 2
          failureThreshold: 2
        resources:
          requests:
            memory: "1024Mi"
          limits:
            memory: "1350Mi"
        imagePullPolicy: Always
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: piano-kube-pull-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
